### ISSUE TITLE
Possible bug in relu.zig

### ISSUE THREAD

**Issue by steppicrew** [SilasMarvin/dnns-from-scratch-in-zig#5]
I'm not that familiar with DNNs and try to use your code to understand it.
While reading your code I stumbled over line 32 in relu.zig.
Is it possible it should read `outputs[i] = 0.01 * grads[i];`?

Thank you

**Comment by SilasMarvin** [comment]
You are absolutely right. Great catch thank you! Updated on: https://github.com/SilasMarvin/dnns-from-scratch-in-zig/commit/9b92997f855c3330ba19ca9bb24484687823b1b1
