### ISSUE TITLE
Build fails for Zig 0.11.0 and master

### ISSUE THREAD

**Issue by jmascarua** [SilasMarvin/dnns-from-scratch-in-zig#6]
I am new to Zig and wanted to start learning by fixing something.
Stumbled with your package which is great. Thanks in advance.

Seems the build syntax changed / upgraded and the one from the repository does not work anymore. Hope this helps.

I tried to create a remote branch and submit a pull request but keep getting authorization errors.

**Comment by SilasMarvin** [comment]
Wow I just realized there are a number of issues and pull requests on this repo. It is now working on the latest version of zig. Thank you for letting me know
